"""user model first pass

Revision ID: 7a9f494f890f
Revises: 82de1cde48fc
Create Date: 2021-12-20 18:19:13.635745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9f494f890f'
down_revision = '82de1cde48fc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
