"""init

Revision ID: 82de1cde48fc
Revises: 
Create Date: 2021-12-20 15:08:54.425452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82de1cde48fc'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
